/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.Controler;
import javax.swing.JTextField;

/**
 *
 * @author debora
 */
public class ViewPostos extends javax.swing.JFrame {

    /**
     * Creates new form ViewPostos
     */
    public ViewPostos() {
        initComponents();
    }
    
    Controler controler = new Controler();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Aba_Cadastro = new javax.swing.JTabbedPane();
        LabelCEP = new javax.swing.JPanel();
        LabelDesc = new javax.swing.JLabel();
        LabelDescricao5 = new javax.swing.JLabel();
        LabelCNPJ = new javax.swing.JLabel();
        LabelRazaoSocial = new javax.swing.JLabel();
        LabelNomeFantasia = new javax.swing.JLabel();
        LabelBandeira = new javax.swing.JLabel();
        LabelImagem = new javax.swing.JLabel();
        LabelEndereco = new javax.swing.JLabel();
        LabelBairro = new javax.swing.JLabel();
        LabelBairro1 = new javax.swing.JLabel();
        BotaoCadastro = new javax.swing.JButton();
        cnpj = new javax.swing.JTextField();
        razaosocial = new javax.swing.JTextField();
        NomeFantasia = new javax.swing.JTextField();
        Bandeira = new javax.swing.JTextField();
        URL = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        bairro = new javax.swing.JTextField();
        cep = new javax.swing.JTextField();
        PainelAlteracoes = new javax.swing.JPanel();
        LabelDescricao2 = new javax.swing.JLabel();
        PainelExclusao = new javax.swing.JPanel();
        LabelDescricao3 = new javax.swing.JLabel();
        PainelVisualizacao = new javax.swing.JPanel();
        LabelDescricao4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelCEP.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        LabelDesc.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        LabelDesc.setForeground(new java.awt.Color(255, 153, 153));
        LabelDesc.setText("Para efetuar o cadastro insira os seguintes dados: ");

        LabelDescricao5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        LabelDescricao5.setForeground(new java.awt.Color(255, 153, 153));
        LabelDescricao5.setText("Cadastrando novo Posto");

        LabelCNPJ.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        LabelCNPJ.setForeground(new java.awt.Color(255, 153, 153));
        LabelCNPJ.setText("CNPJ:");

        LabelRazaoSocial.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        LabelRazaoSocial.setForeground(new java.awt.Color(255, 153, 153));
        LabelRazaoSocial.setText("Razão Social: ");

        LabelNomeFantasia.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        LabelNomeFantasia.setForeground(new java.awt.Color(255, 153, 153));
        LabelNomeFantasia.setText("Nome Fantasia: ");

        LabelBandeira.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        LabelBandeira.setForeground(new java.awt.Color(255, 153, 153));
        LabelBandeira.setText("Bandeira: ");

        LabelImagem.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        LabelImagem.setForeground(new java.awt.Color(255, 153, 153));
        LabelImagem.setText("URL da Imagem do Posto: ");

        LabelEndereco.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        LabelEndereco.setForeground(new java.awt.Color(255, 153, 153));
        LabelEndereco.setText("Endereço:");

        LabelBairro.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        LabelBairro.setForeground(new java.awt.Color(255, 153, 153));
        LabelBairro.setText("Bairro:");

        LabelBairro1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        LabelBairro1.setForeground(new java.awt.Color(255, 153, 153));
        LabelBairro1.setText("CEP: ");

        BotaoCadastro.setText("CADASTRAR");
        BotaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroActionPerformed(evt);
            }
        });

        cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LabelCEPLayout = new javax.swing.GroupLayout(LabelCEP);
        LabelCEP.setLayout(LabelCEPLayout);
        LabelCEPLayout.setHorizontalGroup(
            LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelCEPLayout.createSequentialGroup()
                .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LabelCEPLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LabelCEPLayout.createSequentialGroup()
                                .addComponent(LabelBairro1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LabelCEPLayout.createSequentialGroup()
                                .addComponent(LabelImagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(URL, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelDesc)
                            .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LabelCEPLayout.createSequentialGroup()
                                    .addComponent(LabelCNPJ)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LabelCEPLayout.createSequentialGroup()
                                    .addComponent(LabelBandeira)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Bandeira))
                                .addGroup(LabelCEPLayout.createSequentialGroup()
                                    .addComponent(LabelNomeFantasia)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NomeFantasia))
                                .addGroup(LabelCEPLayout.createSequentialGroup()
                                    .addComponent(LabelRazaoSocial)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(razaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(LabelCEPLayout.createSequentialGroup()
                                    .addComponent(LabelBairro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bairro))
                                .addGroup(LabelCEPLayout.createSequentialGroup()
                                    .addComponent(LabelEndereco)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(LabelCEPLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(BotaoCadastro)))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LabelCEPLayout.createSequentialGroup()
                    .addGap(254, 254, 254)
                    .addComponent(LabelDescricao5)
                    .addContainerGap(263, Short.MAX_VALUE)))
        );
        LabelCEPLayout.setVerticalGroup(
            LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelCEPLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(LabelDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCNPJ)
                    .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRazaoSocial)
                    .addComponent(razaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNomeFantasia)
                    .addComponent(NomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBandeira)
                    .addComponent(Bandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelImagem)
                    .addComponent(URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEndereco)
                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBairro)
                    .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBairro1)
                    .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoCadastro)
                .addContainerGap())
            .addGroup(LabelCEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LabelCEPLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(LabelDescricao5)
                    .addContainerGap(296, Short.MAX_VALUE)))
        );

        Aba_Cadastro.addTab("Cadastrar Posto", LabelCEP);

        LabelDescricao2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        LabelDescricao2.setForeground(new java.awt.Color(255, 153, 153));
        LabelDescricao2.setText("Alterando os dados de um Posto já cadastrado");

        javax.swing.GroupLayout PainelAlteracoesLayout = new javax.swing.GroupLayout(PainelAlteracoes);
        PainelAlteracoes.setLayout(PainelAlteracoesLayout);
        PainelAlteracoesLayout.setHorizontalGroup(
            PainelAlteracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAlteracoesLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(LabelDescricao2)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        PainelAlteracoesLayout.setVerticalGroup(
            PainelAlteracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAlteracoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDescricao2)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        Aba_Cadastro.addTab("Alterar Dados", PainelAlteracoes);

        LabelDescricao3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        LabelDescricao3.setForeground(new java.awt.Color(255, 153, 153));
        LabelDescricao3.setText("Deletando um Posto cadastrado");

        javax.swing.GroupLayout PainelExclusaoLayout = new javax.swing.GroupLayout(PainelExclusao);
        PainelExclusao.setLayout(PainelExclusaoLayout);
        PainelExclusaoLayout.setHorizontalGroup(
            PainelExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelExclusaoLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(LabelDescricao3)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        PainelExclusaoLayout.setVerticalGroup(
            PainelExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelExclusaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDescricao3)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        Aba_Cadastro.addTab("Deletar Posto", PainelExclusao);

        LabelDescricao4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        LabelDescricao4.setForeground(new java.awt.Color(255, 153, 153));
        LabelDescricao4.setText("Visualizar Dados de um Posto Cadastrado");

        javax.swing.GroupLayout PainelVisualizacaoLayout = new javax.swing.GroupLayout(PainelVisualizacao);
        PainelVisualizacao.setLayout(PainelVisualizacaoLayout);
        PainelVisualizacaoLayout.setHorizontalGroup(
            PainelVisualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelVisualizacaoLayout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(LabelDescricao4)
                .addGap(171, 171, 171))
        );
        PainelVisualizacaoLayout.setVerticalGroup(
            PainelVisualizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVisualizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDescricao4)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        Aba_Cadastro.addTab("Mostrar", PainelVisualizacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Aba_Cadastro)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Aba_Cadastro)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroActionPerformed
        // TODO add your handling code here:
        //cnpj, razao_social, nome_fantasia, bandeira, imagem, endereco, bairro, cep
        System.out.println(getCnpj().getText());
        controler.Cadastro(getCnpj().getText(),getRazaosocial().getText(), getNomeFantasia().getText(),getBandeira().getText(),getURL().getText(),getEndereco().getText(),getBairro().getText(),getCep().getText());
    }//GEN-LAST:event_BotaoCadastroActionPerformed

    private void cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPostos().setVisible(true);
            }
            
        });
    }

    public JTextField getCnpj() {
        return cnpj;
    }

    public JTextField getBandeira() {
        return Bandeira;
    }

    public JTextField getNomeFantasia() {
        return NomeFantasia;
    }

    public JTextField getURL() {
        return URL;
    }

    public JTextField getBairro() {
        return bairro;
    }

    public JTextField getCep() {
        return cep;
    }

    public JTextField getEndereco() {
        return endereco;
    }

    public JTextField getRazaosocial() {
        return razaosocial;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Aba_Cadastro;
    private javax.swing.JTextField Bandeira;
    private javax.swing.JButton BotaoCadastro;
    private javax.swing.JLabel LabelBairro;
    private javax.swing.JLabel LabelBairro1;
    private javax.swing.JLabel LabelBandeira;
    private javax.swing.JPanel LabelCEP;
    private javax.swing.JLabel LabelCNPJ;
    private javax.swing.JLabel LabelDesc;
    private javax.swing.JLabel LabelDescricao2;
    private javax.swing.JLabel LabelDescricao3;
    private javax.swing.JLabel LabelDescricao4;
    private javax.swing.JLabel LabelDescricao5;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelImagem;
    private javax.swing.JLabel LabelNomeFantasia;
    private javax.swing.JLabel LabelRazaoSocial;
    private javax.swing.JTextField NomeFantasia;
    private javax.swing.JPanel PainelAlteracoes;
    private javax.swing.JPanel PainelExclusao;
    private javax.swing.JPanel PainelVisualizacao;
    private javax.swing.JTextField URL;
    private javax.swing.JTextField bairro;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cnpj;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField razaosocial;
    // End of variables declaration//GEN-END:variables
}

